### ISSUE TITLE
Automated alerts tab/create new automated alert

### ISSUE THREAD

**Issue by iris-jeong** [iris-jeong/residency-database-app#1]
**Issue:**
![Screenshot](https://user-images.githubusercontent.com/77691556/222922904-19286225-88c0-4442-8a48-f2d06df24f51.png)
The data displayed in the 'Automated Alerts' tab is not in sync with the form for creating automated alerts. 
We display the title and description of the automated alert, however we don't have any inputs for the title or description in the form for creating one.

**Potential Solutions:**
1. When the admin creates a new automated broadcast, we need to add 2 more inputs to the form--1 for the title and 1 for the description of the broadcast. This is because once the broadcast is created, it gets listed under the 'Automated Alerts' tab with a title and description (and frequency but you already have those inputs in the form) so we need that information.
2. Or, we can update the UI of the 'Automated Alerts' tab and have the columns be something like 'Recipients' and 'Message' instead.
3. However, I think a combination of the two would be the best solution where we can have 'Title', 'Message', and 'Frequency' as the columns instead.  
From what the client has mentioned, they're primarily interested in sending out alerts that are meant for everyone which is why I think we can leave out a 'Recipients' column. Instead, in the event they do want to send out an alert to a specific group, they can specify that it's an alert for a subset of residents/fellows within the title, e.g. 'Cardio Upcoming Exam' or 'PGY 1 Onboarding'. 
Additionally, instead of having a 'Description' column, we can have a 'Message' column that shows a preview of the alert's message. That way they don't need to come up with a separate description for the broadcast. I think having part of the message shown would be more informative, especially in conjunction with the title.
![New Solution Screenshot](https://user-images.githubusercontent.com/77691556/222925083-f5e8b611-4889-4de0-8d6c-2a57d3b2e67d.png)

These are some solutions I've come up with but there may be more, and I'm open to hearing your thoughts on it.

**Comment by vmuljo** [comment]
Error was due to mislabeling "To" and "Subject" due to copy and pasting. Should be fixed now. We can discuss the message or description column with the team and Ashley to decide what would be best

**Comment by iris-jeong** [comment]
Okay sounds good!

**Comment by iris-jeong** [comment]
However, we now actually need to add a 'To:' input so they can choose if they want to choose a specific group to send automated requests to. I went back through the recordings today and she mentioned this as a feature they would want so they could send automated notifications to cardiothoracic specialties or pgy 1 years about an upcoming exam, etc.

By the way, what I'm saying now deviates from the Figma design. You did a great job executing the planned version! We just didn't catch the updated feature request during the design phase.

**Comment by vmuljo** [comment]
Got it, issue has been fixed and pushed.
